// Helper: Obtener rango del mes anterior
function getPreviousMonthRange() {
    const now = new Date();

    // Calcular mes anterior
    const previousMonth = now.getMonth() === 0 ? 11 : now.getMonth() - 1;
    const year = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear();

    // Primer día del mes anterior a las 00:00:00
    const firstDay = new Date(year, previousMonth, 1, 0, 0, 0).toISOString();

    // Último día del mes anterior a las 23:59:59
    const lastDayDate = new Date(year, previousMonth + 1, 0, 23, 59, 59);
    const lastDay = lastDayDate.toISOString();

    // Nombre del mes en español
    const monthName = lastDayDate.toLocaleDateString('es-ES', { month: 'long', year: 'numeric' });

    // Validación de fechas para debugging
    console.log('Fecha actual:', now.toISOString());
    console.log('Rango filtrado - Mes anterior:', monthName);
    console.log('Desde:', firstDay);
    console.log('Hasta:', lastDay);

    return { firstDay, lastDay, monthName };
}

Deno.serve(async (req) => {
    const corsHeaders = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Max-Age': '86400',
    };

    if (req.method === 'OPTIONS') {
        return new Response(null, { status: 200, headers: corsHeaders });
    }

    try {
        const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
        const supabaseUrl = Deno.env.get('SUPABASE_URL');
        const resendApiKey = Deno.env.get('RESEND_API_KEY');

        if (!serviceRoleKey || !supabaseUrl) {
            throw new Error('Configuración de Supabase faltante');
        }

        // Verificar si la generación automática está habilitada
        const configResponse = await fetch(
            `${supabaseUrl}/rest/v1/newsletter_config?select=*&limit=1`,
            {
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                }
            }
        );

        if (configResponse.ok) {
            const configs = await configResponse.json();
            if (configs && configs.length > 0 && !configs[0].auto_generation_enabled) {
                return new Response(JSON.stringify({
                    data: {
                        message: 'Generación automática deshabilitada',
                        skipped: true
                    }
                }), {
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' }
                });
            }
        }

        // CORRECCIÓN APLICADA: Filtrar SOLO contenido del mes anterior
        // La función getPreviousMonthRange() calcula correctamente:
        // - Maneja transición de diciembre a enero (año anterior)
        // - Maneja transición de enero a diciembre (año siguiente)  
        // - Funciona correctamente con años bisiestos
        const { firstDay, lastDay, monthName } = getPreviousMonthRange();
        const firstDayOfMonth = firstDay;
        const lastDayOfMonth = lastDay;

        // Fecha actual para metadatos
        const now = new Date();

        // Obtener contenido publicado del newsletter_content
        const contentResponse = await fetch(
            `${supabaseUrl}/rest/v1/newsletter_content?is_published=eq.true&published_at=gte.${firstDayOfMonth}&published_at=lte.${lastDayOfMonth}&order=created_at.asc`,
            {
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                }
            }
        );

        let newsletterContent = [];
        if (contentResponse.ok) {
            newsletterContent = await contentResponse.json();
        }

        // Si no hay contenido específico, extraer de communiques y event_images
        let autoGeneratedContent = {
            news: [],
            events: [],
            surveys: [],
            statistics: [],
            directives: [],
            suggestions: []
        };

        if (!newsletterContent || newsletterContent.length === 0) {
            // Obtener últimos 5 comunicados del mes anterior
            const communiquesResponse = await fetch(
                `${supabaseUrl}/rest/v1/communiques?is_published=eq.true&created_at=gte.${firstDayOfMonth}&created_at=lte.${lastDayOfMonth}&order=created_at.desc&limit=5`,
                {
                    headers: {
                        'Authorization': `Bearer ${serviceRoleKey}`,
                        'apikey': serviceRoleKey,
                    }
                }
            );

            if (communiquesResponse.ok) {
                const communiques = await communiquesResponse.json();
                autoGeneratedContent.news = communiques.map(c => ({
                    id: c.id,
                    type: 'news',
                    title: c.title,
                    content: c.content,
                    excerpt: c.content.substring(0, 200) + '...',
                    image_url: c.image_url || null,
                    include: true,
                    show_full: false
                }));
            }

            // Obtener eventos de la galería del mes anterior
            const eventsResponse = await fetch(
                `${supabaseUrl}/rest/v1/event_images?is_active=eq.true&event_date=gte.${firstDayOfMonth}&event_date=lte.${lastDayOfMonth}&order=event_date.desc&limit=4`,
                {
                    headers: {
                        'Authorization': `Bearer ${serviceRoleKey}`,
                        'apikey': serviceRoleKey,
                    }
                }
            );

            if (eventsResponse.ok) {
                const events = await eventsResponse.json();
                autoGeneratedContent.events = events.map(e => ({
                    id: e.id,
                    type: 'events',
                    title: e.title,
                    content: e.description || 'Evento destacado de nuestra actividad sindical',
                    excerpt: (e.description || '').substring(0, 150),
                    image_url: e.image_url,
                    include: true,
                    show_full: true
                }));
            }

            // Obtener encuestas
            // ... (keep surveys logic)

            // Obtener encuestas activas del mes anterior con estadísticas
            const surveysResponse = await fetch(
                `${supabaseUrl}/rest/v1/surveys?is_active=eq.true&created_at=gte.${firstDayOfMonth}&created_at=lte.${lastDayOfMonth}`,
                {
                    headers: {
                        'Authorization': `Bearer ${serviceRoleKey}`,
                        'apikey': serviceRoleKey,
                    }
                }
            );

            if (surveysResponse.ok) {
                const surveys = await surveysResponse.json();

                // Obtener respuestas para cada encuesta del mes anterior
                const surveyData = await Promise.all(
                    surveys.map(async (survey) => {
                        // Obtener respuestas de esta encuesta del mes anterior
                        const responsesResponse = await fetch(
                            `${supabaseUrl}/rest/v1/survey_responses?survey_id=eq.${survey.id}&created_at=gte.${firstDayOfMonth}&created_at=lte.${lastDayOfMonth}`,
                            {
                                headers: {
                                    'Authorization': `Bearer ${serviceRoleKey}`,
                                    'apikey': serviceRoleKey,
                                }
                            }
                        );

                        let responses = [];
                        let stats = null;

                        if (responsesResponse.ok) {
                            responses = await responsesResponse.json();

                            // Calcular estadísticas
                            const totalResponses = responses.length;
                            if (totalResponses > 0 && survey.options) {
                                const optionCounts = {};
                                responses.forEach(response => {
                                    const optionId = response.selected_option_id;
                                    optionCounts[optionId] = (optionCounts[optionId] || 0) + 1;
                                });

                                const total = Object.values(optionCounts).reduce((sum, count) => sum + count, 0);
                                stats = {
                                    totalResponses,
                                    options: survey.options.map((option, index) => ({
                                        text: option,
                                        votes: optionCounts[index + 1] || 0,
                                        percentage: total > 0 ? Math.round(((optionCounts[index + 1] || 0) / total) * 100) : 0
                                    }))
                                };
                            }
                        }

                        return {
                            type: 'surveys',
                            title: survey.question,
                            totalResponses: responses.length,
                            statistics: stats,
                            created_at: survey.created_at
                        };
                    })
                );

                // Solo incluir encuestas que tuvieron respuestas
                autoGeneratedContent.surveys = surveyData.filter(survey => survey.totalResponses > 0);
            }
        } else {
            // Agrupar contenido existente por tipo
            autoGeneratedContent = {
                news: newsletterContent.filter(c => c.type === 'news'),
                events: newsletterContent.filter(c => c.type === 'events'),
                surveys: newsletterContent.filter(c => c.type === 'surveys'),
                statistics: newsletterContent.filter(c => c.type === 'statistics'),
                directives: newsletterContent.filter(c => c.type === 'directives'),
                suggestions: newsletterContent.filter(c => c.type === 'suggestions')
            };
        }

        // Generar HTML del newsletter usando el nombre del mes anterior
        const title = `Newsletter UGT Towa - ${monthName.charAt(0).toUpperCase() + monthName.slice(1)}`;

        // Obtener QR code activo
        const qrResponse = await fetch(
            `${supabaseUrl}/rest/v1/qr_codes?is_active=eq.true&order=created_at.desc&limit=1`,
            {
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                }
            }
        );

        let qrCode = null;
        if (qrResponse.ok) {
            const qrData = await qrResponse.json();
            if (qrData && qrData.length > 0) {
                qrCode = qrData[0];
            }
        }

        const htmlContent = generateNewsletterHTML(autoGeneratedContent, monthName, qrCode);

        // Crear estructura JSON para newsletter_editions
        const contentJson = {
            html: htmlContent,
            subject: title,
            sections: autoGeneratedContent,
            qrCode: qrCode,
            generatedAt: now.toISOString(),
            itemCount: autoGeneratedContent.news.length + autoGeneratedContent.events.length + autoGeneratedContent.surveys.length
        };

        // Verificar si ya existe un borrador para este mes
        const existingDraftResponse = await fetch(
            `${supabaseUrl}/rest/v1/newsletter_editions?status=eq.draft&title=eq.${encodeURIComponent(title)}`,
            {
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                }
            }
        );

        const existingDrafts = await existingDraftResponse.json();
        let newsletterId = null;
        let isNew = false;

        if (existingDrafts && existingDrafts.length > 0) {
            // Actualizar borrador existente
            newsletterId = existingDrafts[0].id;
            await fetch(`${supabaseUrl}/rest/v1/newsletter_editions?id=eq.${newsletterId}`, {
                method: 'PATCH',
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                    'Content-Type': 'application/json',
                    'Prefer': 'return=minimal'
                },
                body: JSON.stringify({
                    content: contentJson,
                    created_at: now.toISOString()
                })
            });
        } else {
            // Crear nuevo borrador
            isNew = true;
            const createResponse = await fetch(`${supabaseUrl}/rest/v1/newsletter_editions`, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                    'Content-Type': 'application/json',
                    'Prefer': 'return=representation'
                },
                body: JSON.stringify({
                    title,
                    content: contentJson,
                    status: 'draft',
                    auto_generated: true,
                    created_at: now.toISOString()
                })
            });

            if (!createResponse.ok) {
                const errorText = await createResponse.text();
                throw new Error(`Error creando borrador: ${errorText}`);
            }

            const newDraft = await createResponse.json();
            newsletterId = newDraft[0].id;
        }

        // Actualizar fecha de última generación
        await fetch(`${supabaseUrl}/rest/v1/newsletter_config?id=is.not.null`, {
            method: 'PATCH',
            headers: {
                'Authorization': `Bearer ${serviceRoleKey}`,
                'apikey': serviceRoleKey,
                'Content-Type': 'application/json',
                'Prefer': 'return=minimal'
            },
            body: JSON.stringify({
                last_generation_date: now.toISOString(),
                updated_at: now.toISOString()
            })
        });

        // Enviar notificación por email al administrador si hay Resend API key
        if (resendApiKey && isNew) {
            try {
                await fetch('https://api.resend.com/emails', {
                    method: 'POST',
                    headers: {
                        'Authorization': `Bearer ${resendApiKey}`,
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        from: 'UGT Towa Newsletter <onboarding@resend.dev>',
                        to: ['jpedragosa@towapharmaceutical.com'],
                        subject: `[UGT Towa] Nuevo Newsletter Generado - ${title}`,
                        html: `
                            <h2>Nuevo Newsletter Generado Automáticamente</h2>
                            <p><strong>Título:</strong> ${title}</p>
                            <p><strong>Contenido incluido:</strong></p>
                            <ul>
                                <li>Noticias y comunicados: ${autoGeneratedContent.news.length} elementos</li>
                                <li>Eventos de galería: ${autoGeneratedContent.events.length} elementos</li>
                                <li>Encuestas con participación: ${autoGeneratedContent.surveys.length} encuestas</li>
                            </ul>
                            <p><strong>Estado:</strong> Borrador (pendiente de revisión)</p>
                            <p><strong>ID:</strong> ${newsletterId}</p>
                            <p>Puedes revisar y editar el newsletter en el panel de administración:</p>
                            <p><a href="https://x83tsow2k2b8.space.minimax.io/admin/newsletter">Ir al Panel de Newsletter</a></p>
                            <hr />
                            <p style="color: #666; font-size: 12px;">Este email fue generado automáticamente por el sistema de newsletter de UGT Towa.</p>
                        `
                    })
                });
            } catch (emailError) {
                console.error('Error enviando notificación por email:', emailError);
                // No fallar la función si el email falla
            }
        }

        return new Response(JSON.stringify({
            data: {
                message: isNew ? 'Borrador creado exitosamente con contenido automático' : 'Borrador actualizado exitosamente',
                newsletterId,
                title,
                contentItems: autoGeneratedContent.news.length + autoGeneratedContent.events.length + autoGeneratedContent.surveys.length,
                sections: {
                    news: autoGeneratedContent.news.length,
                    events: autoGeneratedContent.events.length,
                    surveys: autoGeneratedContent.surveys.length
                },
                autoGenerated: newsletterContent.length === 0,
                emailSent: isNew && !!resendApiKey
            }
        }), {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });

    } catch (error) {
        console.error('Error generando borrador:', error);

        return new Response(JSON.stringify({
            error: {
                code: 'DRAFT_GENERATION_FAILED',
                message: error.message
            }
        }), {
            status: 500,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
    }
});

function generateNewsletterHTML(contentByType: any, monthName: string, qrCode: any = null): string {
    const siteUrl = 'https://ugttowa.com'; // Base URL para enlaces

    const newsHtml = contentByType.news
        .filter((item: any) => item.include !== false)
        .map((item: any) => `
            <div style="margin-bottom: 25px; padding: 20px; background-color: #f9f9f9; border-left: 5px solid #e50000; border-radius: 4px;">
                <h3 style="margin: 0 0 12px 0; color: #333; font-size: 20px;">${item.title}</h3>
                <p style="margin: 0; color: #555; font-size: 15px;">
                    ${item.show_full ? item.content : item.excerpt}
                </p>
                ${!item.show_full && item.id ? `
                    <div style="margin-top: 15px;">
                        <a href="${siteUrl}/comunicados/${item.id}" style="color: #e50000; font-weight: bold; text-decoration: none; font-size: 14px;">
                            → Más información / Leer noticia completa
                        </a>
                    </div>
                ` : ''}
                ${item.image_url ? `<img src="${item.image_url}" alt="${item.title}" style="max-width: 100%; height: auto; margin-top: 15px; border-radius: 6px; display: block;" />` : ''}
            </div>
        `).join('');

    const eventsHtml = contentByType.events
        .filter((item: any) => item.include !== false)
        .map((item: any) => `
            <div style="margin-bottom: 25px; padding: 20px; background-color: #f9f9f9; border-left: 5px solid #e50000; border-radius: 4px;">
                <h3 style="margin: 0 0 12px 0; color: #333; font-size: 20px;">${item.title}</h3>
                <p style="margin: 0; color: #555; font-size: 15px;">${item.content}</p>
                ${item.image_url ? `<img src="${item.image_url}" alt="${item.title}" style="max-width: 100%; height: auto; margin-top: 15px; border-radius: 6px; display: block;" />` : ''}
            </div>
        `).join('');

    const surveysHtml = (contentByType.surveys || [])
        .filter((item: any) => item.include !== false)
        .map((survey: any) => `
            <div style="margin-bottom: 25px; padding: 20px; background-color: #f9f9f9; border-left: 5px solid #e50000; border-radius: 4px;">
                <h3 style="margin: 0 0 10px 0; color: #333; font-size: 20px;">${survey.title}</h3>
                <p style="margin: 0 0 15px 0; color: #666;"><strong>Total de participantes:</strong> ${survey.totalResponses}</p>
                ${survey.statistics && survey.statistics.options ? `
                    <div style="margin-top: 15px;">
                        ${survey.statistics.options.map((option: any) => `
                            <div style="margin-bottom: 12px; background-color: #ffffff; padding: 12px; border: 1px solid #eee; border-radius: 6px;">
                                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
                                    <span style="font-weight: bold; color: #444;">${option.text}</span>
                                    <span style="color: #e50000; font-weight: bold;">${option.percentage}%</span>
                                </div>
                                <div style="background-color: #eee; height: 10px; border-radius: 5px; overflow: hidden;">
                                    <div style="background-color: #e50000; height: 100%; width: ${option.percentage}%; border-radius: 5px;"></div>
                                </div>
                                <p style="margin: 5px 0 0 0; font-size: 12px; color: #999;">${option.votes} votos registrados</p>
                            </div>
                        `).join('')}
                    </div>
                ` : ''}
            </div>
        `).join('');

    return `
    <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; background-color: #ffffff; padding: 20px; border-radius: 8px;">
        <div style="background-color: #e50000; color: white; padding: 30px; text-align: center; border-radius: 8px 8px 0 0; margin-bottom: 30px;">
            <h1 style="margin: 0; font-size: 28px;">Newsletter UGT Towa</h1>
            <p style="margin: 5px 0 0 0; opacity: 0.9;">${monthName}</p>
        </div>

        ${newsHtml ? `
        <div style="margin-bottom: 40px;">
            <h2 style="color: #e50000; font-size: 22px; font-weight: bold; border-bottom: 2px solid #e50000; padding-bottom: 10px; margin-bottom: 20px; text-transform: uppercase;">Noticias y Comunicados</h2>
            ${newsHtml}
        </div>
        ` : ''}

        ${eventsHtml ? `
        <div style="margin-bottom: 40px;">
            <h2 style="color: #e50000; font-size: 22px; font-weight: bold; border-bottom: 2px solid #e50000; padding-bottom: 10px; margin-bottom: 20px; text-transform: uppercase;">Galería de Eventos</h2>
            ${eventsHtml}
        </div>
        ` : ''}

        ${surveysHtml ? `
        <div style="margin-bottom: 40px;">
            <h2 style="color: #e50000; font-size: 22px; font-weight: bold; border-bottom: 2px solid #e50000; padding-bottom: 10px; margin-bottom: 20px; text-transform: uppercase;">Resultados de Encuestas</h2>
            ${surveysHtml}
        </div>
        ` : ''}

        ${qrCode ? `
        <div style="text-align: center; margin-top: 50px; padding: 30px; background-color: #fdf2f2; border: 2px dashed #e50000; border-radius: 12px;">
            <h2 style="color: #e50000; font-size: 24px; font-weight: bold; margin-bottom: 20px;">¡SÚMATE A UGT!</h2>
            <div style="display: inline-block; padding: 15px; background-color: white; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
                <img src="${qrCode.image_url}" alt="QR Afiliación" style="max-width: 180px; width: 100%; height: auto; display: block;" />
            </div>
            ${qrCode.description ? `<p style="margin-top: 20px; color: #666; font-size: 15px; font-style: italic;">${qrCode.description}</p>` : ''}
            <p style="margin-top: 15px; color: #e50000; font-weight: bold;">Escanea este código o contacta con tu delegado</p>
        </div>
        ` : ''}

        <div style="margin-top: 60px; padding-top: 30px; border-top: 2px solid #eee; text-align: center; color: #666; font-size: 13px;">
            <p style="margin-bottom: 10px;"><strong>Sección Sindical UGT - Towa Pharmaceutical Europe</strong></p>
            <p style="margin: 5px 0;">Email: <a href="mailto:jpedragosa@towapharmaceutical.com" style="color: #e50000; text-decoration: none;">jpedragosa@towapharmaceutical.com</a></p>
            <p style="margin: 5px 0;">Martorelles, Barcelona</p>
            <div style="margin-top: 20px; font-size: 11px; color: #aaa;">
                <p>© ${new Date().getFullYear()} UGT Towa. Enviado a través del Portal del Afiliado.</p>
                <p>Si no deseas recibir más comunicaciones, puedes darte de baja desde el portal.</p>
            </div>
        </div>
    </div>
    `.trim();
}

/*
 * CAMBIOS APLICADOS - CORRECCIÓN FILTRO TEMPORAL
 * 
 * Fecha: 2025-11-16
 * 
 * PROBLEMA IDENTIFICADO:
 * El sistema filtraba correctamente newsletter_content por mes anterior,
 * pero NO aplicaba filtro temporal a communiques y event_images.
 * 
 * SOLUCIONES IMPLEMENTADAS:
 * 
 * 1. Función getPreviousMonthRange():
 *    - Calcula correctamente el rango del mes anterior
 *    - Maneja transición diciembre/enero (cambio de año)
 *    - Maneja años bisiestos automáticamente
 *    - Incluye logs para debugging
 * 
 * 2. Filtros temporales aplicados:
 *    - newsletter_content: filtrado por published_at (línea 78)
 *    - communiques: filtrado por created_at (línea 104)
 *    - event_images: filtrado por event_date (línea 125)
 * 
 * 3. Casos especiales cubiertos:
 *    - Fecha actual = 2025-01-15 → rango = 2024-12-01 a 2024-12-31
 *    - Fecha actual = 2025-12-01 → rango = 2025-11-01 a 2025-11-30
 *    - Años bisiestos: enero de años bisiestos usa diciembre del año anterior
 * 
 * RESULTADO:
 * El sistema ahora filtra correctamente SOLO contenido del mes anterior
 * en todas las fuentes de datos, eliminando contenido actual.
 */
